In [2]:
import numpy as np
import pandas as pd


In [107]:
food=pd.read_csv('../data/Cal/Food_Display_Table.csv')
food.head()

Food_Code                      Display_Name  Portion_Default  \
0   12350000                    Sour cream dip                1   
1   13110100                Ice cream, regular                1   
2   13110120                   Ice cream, rich                1   
3   13110200              Soft serve ice cream                1   
4   13120100  Ice cream bar, chocolate covered                1   

   Portion_Amount Portion_Display_Name  Factor  Increment  Multiplier  \
0            0.25                  cup    0.25       0.25        1.00   
1            1.00                  cup    1.00       0.25        0.25   
2            1.00                  cup    1.00       0.25        0.25   
3            1.00                  cup    1.00       0.25        0.25   
4            1.00  bar (bar = 3 fl oz)    1.00       0.50        0.50   

    Grains  Whole_Grains       ...           Milk   Meats  Soy  Drybeans_Peas  \
0  0.04799             0       ...        0.00000  0.0000    0              0   
1  0.00000             0       ...        0.29393  0.0000    0              0   
2  0.00000             0       ...        0.25160  0.0962    0              0   
3  0.00000             0       ...        0.38233  0.0000    0              0   
4  0.00000             0       ...        0.09744  0.0000    0              0   

   Oils  Solid_Fats  Added_Sugars  Alcohol  Calories  Saturated_Fats  
0     0   105.64850       1.57001        0    133.65         7.36898  
1     0   130.99968      95.20488        0    267.33         9.03070  
2     0   213.06672      96.10340        0    368.52        15.28840  
3     0   170.39808     123.83793        0    347.73        11.74670  
4     0   112.32144      45.54761        0    169.12         9.58720  

[5 rows x 26 columns]

In [108]:
plt.figure(0)
plt.heatmap(food.values)
plt.show

NameError: name 'plt' is not defined

In [11]:
food.shape

(2014, 26)

In [12]:
food.columns

Index([u'Food_Code', u'Display_Name', u'Portion_Default', u'Portion_Amount',
       u'Portion_Display_Name', u'Factor', u'Increment', u'Multiplier',
       u'Grains', u'Whole_Grains', u'Vegetables', u'Orange_Vegetables',
       u'Drkgreen_Vegetables', u'Starchy_vegetables', u'Other_Vegetables',
       u'Fruits', u'Milk', u'Meats', u'Soy', u'Drybeans_Peas', u'Oils',
       u'Solid_Fats', u'Added_Sugars', u'Alcohol', u'Calories',
       u'Saturated_Fats'],
      dtype='object')

In [17]:
food['Display_Name']

0                           Sour cream dip
1                       Ice cream, regular
2                          Ice cream, rich
3                     Soft serve ice cream
4         Ice cream bar, chocolate covered
5         Ice cream bar, chocolate covered
6                       Ice cream sandwich
7                          Light ice cream
8               Light soft serve ice cream
9                 Light ice cream sandwich
10                     Light ice cream bar
11                        Light fudgesicle
12                                 Sherbet
13                                 Sherbet
14             Low fat, low sugar ice milk
15                 Cheese (cheddar, Swiss)
16                 Cheese (cheddar, Swiss)
17                     Feta or goat cheese
18                     Feta or goat cheese
19           Mozzarella cheese (part skim)
20                Low fat cheddar or Swiss
21                Low fat cheddar or Swiss
22                 Cottage cheese, creamed
23         

In [21]:
foodo=pd.read_csv('../data/Cal/Foods_Needing_Condiments_Table.csv')
foodo.columns

Index([u'Survey_Food_Code', u'display_name', u'cond_1_code', u'cond_1_name',
       u'cond_2_code', u'cond_2_name', u'cond_3_code', u'cond_3_name',
       u'cond_4_code', u'cond_4_name', u'cond_5_code', u'cond_5_name'],
      dtype='object')

In [23]:
foodo['display_name']

0                                100% Whole Wheat Bagel"
1                               Beef burrito (no beans):
2                           Chicken & cheese quesadilla:
3                                 Ground beef (95% lean)
4                                 Ground beef (90% lean)
5        Beef steak, grilled or broiled (eat lean & fat)
6         Beef steak, grilled or broiled (eat lean only)
7                     Beef steak, fried (eat lean & fat)
8                      Beef steak, fried (eat lean only)
9         Beef steak, breaded and fried (eat lean & fat)
10         Beef steak, breaded and fried (eat lean only)
11                           Roast beef (eat lean & fat)
12                            Roast beef (eat lean only)
13                       Ground beef (75% lean, regular)
14                                Ground beef (80% lean)
15                                Ground beef (85% lean)
16     Fried chicken, boneless and battered (skin eaten)
17          Baked or roasted ch

In [94]:
fed=pd.read_csv('../data/Cal/lu_Condiment_Food_Table.csv')
fed.head(20)

survey_food_code                         display_name  \
0           11111000                           Whole milk   
1           11111000                           Whole milk   
2           11112210                    1% milk (low fat)   
3           11112210                    1% milk (low fat)   
4           11113000                 Fat free milk (skim)   
5           11113000                 Fat free milk (skim)   
6           11320000   Soymilk, plain (calcium fortified)   
7           12110100  Light cream (coffee or table cream)   
8           12120100                          Half & Half   
9           12140000            Whipped cream (sweetened)   
10          12210200         Coffee Mate creamer (liquid)   
11          12210250    Coffee Mate Lite creamer (liquid)   
12          12310100                           Sour cream   
13          14104010              Cheese (cheddar, Swiss)   
14          14109030             Low fat cheddar or Swiss   
15          14301010               Cream cheese (regular)   
16          14303010                 Low fat cream cheese   
17          14420100                 Cheese spread or dip   
18          27111410         Chili con carne (with beans)   
19          28500000                        Chicken gravy   

   condiment_portion_size  condiment_portion_code  condiment_grains  \
0                1/2  cup                   10205           0.00000   
1           2 Tablespoons                   30000           0.00000   
2                1/2  cup                   10205           0.00000   
3           2 Tablespoons                   30000           0.00000   
4                1/2  cup                   10205           0.00000   
5           2 Tablespoons                   30000           0.00000   
6                1/2  cup                   10205           0.00000   
7                  2 Tbsp                   30000           0.00000   
8                  2 Tbsp                   30000           0.00000   
9                 1/4 cup                   10205           0.00000   
10                 2 Tbsp                   30000           0.00000   
11                 2 Tbsp                   30000           0.00000   
12                 2 Tbsp                   60597           0.00000   
13         1 slice (1 oz)                   61937           0.00000   
14         1 slice (1 oz)                   61937           0.00000   
15                 1 Tbsp                   21000           0.00000   
16                 1 Tbsp                   21000           0.00000   
17          2 Tablespoons                   10205           0.00000   
18                1/4 cup                   10205           0.00000   
19                1/4 cup                   10205           0.30048   

    condiment_whole_grains  condiment_vegetables  condiment_dkgreen  \
0                        0               0.00000                  0   
1                        0               0.00000                  0   
2                        0               0.00000                  0   
3                        0               0.00000                  0   
4                        0               0.00000                  0   
5                        0               0.00000                  0   
6                        0               0.00000                  0   
7                        0               0.00000                  0   
8                        0               0.00000                  0   
9                        0               0.00000                  0   
10                       0               0.00000                  0   
11                       0               0.00000                  0   
12                       0               0.00000                  0   
13                       0               0.00000                  0   
14                       0               0.00000                  0   
15                       0               0.00000                  0   
16                     

In [26]:
np.unique(fed['condiment_portion_size'])

array(['1 Tbsp', '1 leaf', '1 slice', '1 slice (1 oz)', '1 tsp',
       '1/2  cup', '1/4 cup', '2 Tablespoons', '2 Tbsp', '2 tsp'],
      dtype=object)

In [44]:
foodfind='Burger'

FoodName=np.asarray((fed['display_name']))
print FoodName.shape

(63,)


In [41]:
foodSer='milk'
Bucket=[]
for foo in FoodName:
    for ix in foo.split():
        if foodSer==ix:
            Bucket.append(foo)
            
print Bucket

['1% milk (low fat)', 'Fat free milk (skim)', 'Whole milk']


In [59]:
for buck in Bucket:
    for foodid in range(FoodName.shape[0]):
        if buck==FoodName[foodid]:
            FoodList.append(fed['survey_food_code'].loc[foodid])
            
            print '*'*20
            
print FoodList

11112210 ---------> 51.24
********************
11112210 ---------> 12.81
********************
11113000 ---------> 41.65
********************
11113000 ---------> 10.4125
********************
11111000 ---------> 73.2
********************
11111000 ---------> 18.3
********************


In [85]:
FoodList=[]
FoodListId=[]
for buck in Bucket:
    for foodid in range(FoodName.shape[0]):
        if buck==FoodName[foodid]:
            FoodList.append(fed['survey_food_code'].loc[foodid])
            FoodListId.append(foodid)
print (FoodList)
print FoodListId

[11112210, 11112210, 11113000, 11113000, 11111000, 11111000]
[2, 3, 4, 5, 0, 1]


In [89]:
for ix in range(len(FoodList)):
    done =mark(done,ix,FoodListId,FoodList)
    print fed['display_name'].loc[FoodListId[ix]]

1% milk (low fat)
1% milk (low fat)
Fat free milk (skim)
Fat free milk (skim)
Whole milk
Whole milk


In [ ]:
def remove(FoodListId,FoodList):
    for ix in FoodList:
        if 

In [93]:
FoodList=np.unique(FoodList)
print FoodList
diction={}
for ix in FoodList:
    if diction(ix)==None:
        diction(ix)=

[11111000 11112210 11113000]


In [65]:
def display_data(FoodList,FoodListId):
    for fl,fli in zip(FoodList,FoodListId):
        print fl,"--->",fli
    #print fed['display_name'].loc[]

In [84]:
lis=np.zeros(len(FoodList))
print len(FoodList)
print lis


6
[0. 0. 0. 0. 0. 0.]


11111000 ---> 2
11112210 ---> 3
11113000 ---> 4


In [242]:
dataset=pd.read_csv('../data/sex_age_diagnosis.csv')
dataset['diagnosis'].loc[1]

'Gastroesophageal reflux  |  GERD, heartburn'

In [219]:
prob=[]
for ix in dataset['diagnosis']:
    for i in ix.split('|'):
        prob.append(i)

print (np.unique(prob,return_counts=True)[1])

[1 1 1 ... 1 1 1]


In [198]:
np.unique(dataset['age'])

array(['13', '13-17', '18-24', '25-34', '35-44', '44-54', '55-64', '65+',
       '>65+'], dtype=object)

In [185]:
col=[]
for ix in dataset.columns:
    col.append(ix)
    
# print col
# print dataset['\xef\xbb\xbf"sex"']

In [170]:
print dataset.shape

(1887, 3)


In [139]:
AgeGroups = np.unique(dataset['age'],return_counts=True)

In [238]:
bucket={'M':{'13':[], '13-17':[], '18-24':[], '25-34':[], '35-44':[], '44-54':[], '55-64':[], '65+':[],
       '>65+':[]},'F':{'13':[], '13-17':[], '18-24':[], '25-34':[], '35-44':[], '44-54':[], '55-64':[], '65+':[],
       '>65+':[]}}


In [239]:
def Add(abc,lis):
    for ix in abc.split('|'):
        lis.append(ix)
    return lis

In [ ]:
Add('Gastroesophageal reflux  |  GERD, heartburn')

In [240]:
for ix in range(dataset.shape[0]):
    curage=dataset['age'].loc[ix]
    if dataset['\xef\xbb\xbf"sex"'].loc[ix]=='M':
        bucket['M'][curage]=Add(dataset['diagnosis'].loc[ix],bucket['M'][curage])
    elif dataset['\xef\xbb\xbf"sex"'].loc[ix]=='F':
        bucket['F'][curage]=Add(dataset['diagnosis'].loc[ix],bucket['F'][curage])
        

#print np.unique(bucket['M']['13-17'],return_counts=True)

In [241]:
for ix in bucket:
    for i in bucket[ix]:
        for ii in bucket[ix][i]:
            #print ii
            pass
            
(bucket['M']['13'])

[]

In [208]:
np.unique(foo2['diagnosis'],return_counts=True)

(array(['AC joint separation  |  acromioclavicular joint separation  |  closed separation of acromioclavicular joint',
        'ACE inhibitor induced cough  |  blood pressure medication side effect  |  Drug-induced cough  |  Drug reaction: ACE inhibitor',
        'Abdominal aortic aneurysm  |  (enlarged major blood vessel)',
        'Abdominal swelling', 'Abdominal trauma',
        'Abrasions  |   (scrapes)',
        'Achilles tendon rupture  |  (heel tendon tear)',
        'Achilles tendonitis  |   (heel tendon inflammation)',
        'Acid   |  LSD abuse',
        'Acidosis  |   (excessive acid in the body)',
        'Acoustic neuroma  |  (ear nerve tumor)',
        'Acute angle closure glaucoma  |  increased inner eye pressure',
        'Acute fatty liver of pregnancy',
        'Adjustment disorder  |   (poor adjustment to life stressor)',
        'Alcohol   |  ethanol abuse', 'Alcohol   |  ethanol intoxication',
        'Alcohol   |  ethanol poisoning  |   (overdose)',
        'Alc